services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=weblibrary'
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weblibrary-network

  weblibrary:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/weblibrary'
      - 'SPRING_DATASOURCE_HIKARI_USERNAME=${DB_USERNAME}'
      - 'SPRING_DATASOURCE_HIKARI_PASSWORD=${DB_PASSWORD}'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - weblibrary-network

networks:
  weblibrary-network:
    driver: bridge
volumes:
  postgres_data: