spring:
  application:
    name: WebLibrary
  datasource:
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
