spring:
  application:
    name: WebLibrary
  datasource:
    hikari:
      username: ${db_username}
      password: ${db_password}
    url: jdbc:postgresql://localhost:5432/weblibrary
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none