spring:
  application:
    name: WebLibrary
  datasource:
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
